version: '3.8'
services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=muadmaalim@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--entrypoints.traefik.address=:8081"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`proxy.muadmaalim.buzz`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8081"
    networks:
      - web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    environment:
      DOMAIN: muadmaalim.buzz
      ENVIRONMENT: production
      DATABASE_URL: postgres://app:hng123@db:5432/app
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`muadmaalim.buzz/api`)" #don't forget to change this since you added ("/api") it should be muadmaalim.buzz
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - web

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`www.muadmaalim.buzz`) || Host(`muadmaalim.buzz`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=4173"
    networks:
      - web

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: hng123
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web

  adminer:
    image: adminer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`db.muadmaalim.buzz`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    networks:
      - web

volumes:
  postgres_data:
  letsencrypt:

networks:
  web:
